import Foundation

/// Represents flexible JSON values in schemas and parameters.
public enum JSONValue: Codable, Sendable, Equatable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case object([String: JSONValue])
    case array([JSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let b = try? container.decode(Bool.self) {
            self = .bool(b)
        } else if let n = try? container.decode(Double.self) {
            self = .number(n)
        } else if let s = try? container.decode(String.self) {
            self = .string(s)
        } else if let arr = try? container.decode([JSONValue].self) {
            self = .array(arr)
        } else if let dict = try? container.decode([String: JSONValue].self) {
            self = .object(dict)
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Invalid JSONValue")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let s): try container.encode(s)
        case .number(let n): try container.encode(n)
        case .bool(let b): try container.encode(b)
        case .object(let o): try container.encode(o)
        case .array(let a): try container.encode(a)
        case .null: try container.encodeNil()
        }
    }
}

/// Image URL container for multimodal content parts.
public struct ImageURL: Codable, Sendable, Equatable {
    public var url: String
    public var detail: String?

    public init(url: String, detail: String? = nil) {
        self.url = url
        self.detail = detail
    }
}

/// Individual content parts within a multimodal chat message.
public enum MessageContentPart: Codable, Sendable, Equatable {
    case text(String)
    case imageUrl(ImageURL)

    enum CodingKeys: String, CodingKey {
        case type
        case text
        case image_url
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(String.self, forKey: .type)
        if type == "text" {
            let text = try container.decode(String.self, forKey: .text)
            self = .text(text)
        } else if type == "image_url" {
            let img = try container.decode(ImageURL.self, forKey: .image_url)
            self = .imageUrl(img)
        } else {
            let text = (try? container.decode(String.self, forKey: .text)) ?? ""
            self = .text(text)
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .text(let str):
            try container.encode("text", forKey: .type)
            try container.encode(str, forKey: .text)
        case .imageUrl(let img):
            try container.encode("image_url", forKey: .type)
            try container.encode(img, forKey: .image_url)
        }
    }
}

/// Function definition inside a ToolDefinition.
public struct FunctionDefinition: Codable, Sendable, Equatable {
    public var name: String
    public var description: String?
    public var parameters: JSONValue?

    public init(name: String, description: String? = nil, parameters: JSONValue? = nil) {
        self.name = name
        self.description = description
        self.parameters = parameters
    }
}

/// Tool definition compliant with the OpenAI specification.
public struct ToolDefinition: Codable, Sendable, Equatable {
    public var type: String
    public var function: FunctionDefinition

    public init(type: String = "function", function: FunctionDefinition) {
        self.type = type
        self.function = function
    }
}

/// Function call parameters generated by the model.
public struct FunctionCall: Codable, Sendable, Equatable {
    public var name: String
    public var arguments: String

    public init(name: String, arguments: String) {
        self.name = name
        self.arguments = arguments
    }
}

/// Tool call entity generated by the assistant.
public struct ToolCall: Codable, Sendable, Equatable {
    public var id: String
    public var type: String
    public var function: FunctionCall

    public init(
        id: String = "call_" + UUID().uuidString.replacingOccurrences(of: "-", with: "").prefix(12),
        type: String = "function",
        function: FunctionCall
    ) {
        self.id = id
        self.type = type
        self.function = function
    }
}

/// Incremental function call chunk for streaming tool calls.
public struct FunctionCallChunk: Codable, Sendable, Equatable {
    public var name: String?
    public var arguments: String?

    public init(name: String? = nil, arguments: String? = nil) {
        self.name = name
        self.arguments = arguments
    }
}

/// Streaming chunk for tool calls.
public struct ToolCallChunk: Codable, Sendable, Equatable {
    public var index: Int
    public var id: String?
    public var type: String?
    public var function: FunctionCallChunk?

    public init(index: Int = 0, id: String? = nil, type: String? = "function", function: FunctionCallChunk? = nil) {
        self.index = index
        self.id = id
        self.type = type
        self.function = function
    }
}

/// A single message entity within a chat completion request or response.
public struct ChatMessage: Codable, Sendable, Equatable {
    public var role: String
    public var content: String
    public var contentParts: [MessageContentPart]?
    public var name: String?
    public var reasoning_content: String?
    public var reasoning: String?
    public var tool_calls: [ToolCall]?
    public var tool_call_id: String?

    enum CodingKeys: String, CodingKey {
        case role
        case content
        case name
        case reasoning_content
        case reasoning
        case tool_calls
        case tool_call_id
    }

    public init(
        role: String,
        content: String,
        contentParts: [MessageContentPart]? = nil,
        name: String? = nil,
        reasoning_content: String? = nil,
        reasoning: String? = nil,
        tool_calls: [ToolCall]? = nil,
        tool_call_id: String? = nil
    ) {
        self.role = role
        self.content = content
        self.contentParts = contentParts
        self.name = name
        self.reasoning_content = reasoning_content
        self.reasoning = reasoning ?? reasoning_content
        self.tool_calls = tool_calls
        self.tool_call_id = tool_call_id
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.role = try container.decode(String.self, forKey: .role)
        self.name = try container.decodeIfPresent(String.self, forKey: .name)
        self.reasoning_content = try container.decodeIfPresent(String.self, forKey: .reasoning_content)
        self.reasoning = try container.decodeIfPresent(String.self, forKey: .reasoning) ?? self.reasoning_content
        self.tool_calls = try container.decodeIfPresent([ToolCall].self, forKey: .tool_calls)
        self.tool_call_id = try container.decodeIfPresent(String.self, forKey: .tool_call_id)

        if let stringContent = try? container.decode(String.self, forKey: .content) {
            self.content = stringContent
            self.contentParts = nil
        } else if let parts = try? container.decode([MessageContentPart].self, forKey: .content) {
            self.contentParts = parts
            let textParts = parts.compactMap { part -> String? in
                if case .text(let t) = part { return t }
                return nil
            }
            self.content = textParts.joined(separator: "\n")
        } else {
            self.content = ""
            self.contentParts = nil
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(role, forKey: .role)
        if let parts = contentParts, !parts.isEmpty {
            try container.encode(parts, forKey: .content)
        } else {
            try container.encode(content, forKey: .content)
        }
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(reasoning_content, forKey: .reasoning_content)
        try container.encodeIfPresent(reasoning, forKey: .reasoning)
        try container.encodeIfPresent(tool_calls, forKey: .tool_calls)
        try container.encodeIfPresent(tool_call_id, forKey: .tool_call_id)
    }

    public var textContent: String {
        content
    }

    public var imageUrls: [String] {
        var urls: [String] = []

        if let parts = contentParts {
            for part in parts {
                if case .imageUrl(let img) = part, !urls.contains(img.url) {
                    urls.append(img.url)
                }
            }
        }

        if !content.isEmpty {
            let lines = content.components(separatedBy: .newlines)
            for line in lines {
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                if trimmed.hasPrefix("@image:") {
                    let path = String(trimmed.dropFirst("@image:".count)).trimmingCharacters(in: .whitespaces)
                    if !path.isEmpty && !urls.contains(path) {
                        urls.append(path)
                    }
                }
            }

            // Match image_url: <path> even with spaces (e.g. /Users/.../Application Support/...)
            if let regex = try? NSRegularExpression(pattern: "image_url:\\s*([^\\]\\r\\n]+)") {
                let nsString = content as NSString
                let matches = regex.matches(in: content, range: NSRange(location: 0, length: nsString.length))
                for match in matches {
                    if match.numberOfRanges > 1 {
                        let rawPath = nsString.substring(with: match.range(at: 1)).trimmingCharacters(in: .whitespacesAndNewlines)
                        let cleanPath = rawPath.trimmingCharacters(in: CharacterSet(charactersIn: "\"\'"))
                        if !cleanPath.isEmpty && !urls.contains(cleanPath) {
                            urls.append(cleanPath)
                        }
                    }
                }
            }

            // Match Hermes MEDIA: directive
            if let regex = try? NSRegularExpression(pattern: "MEDIA:\\s*([^\\]\\r\\n]+)") {
                let nsString = content as NSString
                let matches = regex.matches(in: content, range: NSRange(location: 0, length: nsString.length))
                for match in matches {
                    if match.numberOfRanges > 1 {
                        let rawPath = nsString.substring(with: match.range(at: 1)).trimmingCharacters(in: .whitespacesAndNewlines)
                        let cleanPath = rawPath.trimmingCharacters(in: CharacterSet(charactersIn: "\"\'"))
                        if !cleanPath.isEmpty && !urls.contains(cleanPath) {
                            urls.append(cleanPath)
                        }
                    }
                }
            }
        }

        return urls
    }
}

/// Request parameters for chat completions compliant with the OpenAI specification.
public struct ChatCompletionRequest: Codable, Sendable {
    public var model: String?
    public var messages: [ChatMessage]
    public var temperature: Double?
    public var max_tokens: Int?
    public var max_completion_tokens: Int?
    public var stream: Bool?
    public var top_p: Double?
    public var reasoning_effort: String?
    public var tools: [ToolDefinition]?
    public var tool_choice: JSONValue?

    public init(
        model: String? = nil,
        messages: [ChatMessage] = [],
        temperature: Double? = nil,
        max_tokens: Int? = nil,
        max_completion_tokens: Int? = nil,
        stream: Bool? = nil,
        top_p: Double? = nil,
        reasoning_effort: String? = nil,
        tools: [ToolDefinition]? = nil,
        tool_choice: JSONValue? = nil
    ) {
        self.model = model
        self.messages = messages
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.max_completion_tokens = max_completion_tokens
        self.stream = stream
        self.top_p = top_p
        self.reasoning_effort = reasoning_effort
        self.tools = tools
        self.tool_choice = tool_choice
    }

    public var effectiveMaxTokens: Int? {
        max_completion_tokens ?? max_tokens
    }

    public var topP: Double? {
        top_p
    }
}

/// Token usage metadata for completions.
public struct UsageInfo: Codable, Sendable, Equatable {
    public var prompt_tokens: Int
    public var completion_tokens: Int
    public var total_tokens: Int

    public init(prompt_tokens: Int = 0, completion_tokens: Int = 0, total_tokens: Int = 0) {
        self.prompt_tokens = prompt_tokens
        self.completion_tokens = completion_tokens
        self.total_tokens = total_tokens
    }
}

/// A completion choice returned by the model.
public struct ChatChoice: Codable, Sendable, Equatable {
    public var index: Int
    public var message: ChatMessage
    public var finish_reason: String?

    public init(index: Int = 0, message: ChatMessage, finish_reason: String? = "stop") {
        self.index = index
        self.message = message
        self.finish_reason = finish_reason
    }
}

/// Full chat completion response object.
public struct ChatCompletionResponse: Codable, Sendable {
    public var id: String
    public var object: String
    public var created: Int
    public var model: String
    public var choices: [ChatChoice]
    public var usage: UsageInfo?

    public init(
        id: String = "chatcmpl-" + UUID().uuidString,
        object: String = "chat.completion",
        created: Int = Int(Date().timeIntervalSince1970),
        model: String = "siri-flash",
        choices: [ChatChoice],
        usage: UsageInfo? = nil
    ) {
        self.id = id
        self.object = object
        self.created = created
        self.model = model
        self.choices = choices
        self.usage = usage
    }
}

/// Incremental content delta for streaming chunks.
public struct ChunkDelta: Codable, Sendable, Equatable {
    public var role: String?
    public var content: String?
    public var reasoning_content: String?
    public var reasoning: String?
    public var tool_calls: [ToolCallChunk]?

    public init(
        role: String? = nil,
        content: String? = nil,
        reasoning_content: String? = nil,
        reasoning: String? = nil,
        tool_calls: [ToolCallChunk]? = nil
    ) {
        self.role = role
        self.content = content
        self.reasoning_content = reasoning_content
        self.reasoning = reasoning ?? reasoning_content
        self.tool_calls = tool_calls
    }
}

/// A choice object within a streaming completion chunk.
public struct ChunkChoice: Codable, Sendable, Equatable {
    public var index: Int
    public var delta: ChunkDelta
    public var finish_reason: String?

    public init(index: Int = 0, delta: ChunkDelta, finish_reason: String? = nil) {
        self.index = index
        self.delta = delta
        self.finish_reason = finish_reason
    }
}

/// A streaming chunk payload sent via Server-Sent Events.
public struct ChatCompletionChunk: Codable, Sendable {
    public var id: String
    public var object: String
    public var created: Int
    public var model: String
    public var choices: [ChunkChoice]
    public var usage: UsageInfo?

    public init(
        id: String,
        object: String = "chat.completion.chunk",
        created: Int = Int(Date().timeIntervalSince1970),
        model: String = "siri-flash",
        choices: [ChunkChoice],
        usage: UsageInfo? = nil
    ) {
        self.id = id
        self.object = object
        self.created = created
        self.model = model
        self.choices = choices
        self.usage = usage
    }
}

/// Model descriptor returned in model listing queries.
public struct ModelObject: Codable, Sendable {
    public var id: String
    public var object: String
    public var created: Int
    public var owned_by: String

    public init(
        id: String,
        object: String = "model",
        created: Int = 1717977600,
        owned_by: String = "apple"
    ) {
        self.id = id
        self.object = object
        self.created = created
        self.owned_by = owned_by
    }
}

/// List of available models.
public struct ModelListResponse: Codable, Sendable {
    public var object: String
    public var data: [ModelObject]

    public init(object: String = "list", data: [ModelObject]) {
        self.object = object
        self.data = data
    }
}
